# Generated by Django 5.1.3 on 2024-11-14 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_name', models.CharField(max_length=10)),
                ('day_code', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='SeatCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='railways.day')),
            ],
        ),
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_seats', models.IntegerField()),
                ('booked_seats', models.IntegerField(default=0)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journeys', to='railways.date')),
            ],
        ),
        migrations.CreateModel(
            name='JourneySegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('journey_length', models.DurationField()),
                ('price_segment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='railways.journey')),
                ('arrival_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segment_arrivals', to='railways.station')),
                ('departure_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segment_departures', to='railways.station')),
            ],
        ),
        migrations.CreateModel(
            name='JourneySegmentSeatCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_seats', models.IntegerField()),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('journey_segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segment_seat_categories', to='railways.journeysegment')),
                ('seat_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segment_seat_categories', to='railways.seatcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=10)),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('journey_length', models.DurationField()),
                ('arrival_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='train_arrivals', to='railways.station')),
                ('days_running', models.ManyToManyField(related_name='running_trains', to='railways.day')),
                ('departure_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='train_departures', to='railways.station')),
            ],
        ),
        migrations.AddField(
            model_name='journey',
            name='train',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journeys', to='railways.train'),
        ),
        migrations.CreateModel(
            name='TrainSeatCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_seats', models.IntegerField()),
                ('available_seats', models.IntegerField()),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('seat_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='train_seat_categories', to='railways.seatcategory')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='train_seat_categories', to='railways.train')),
            ],
        ),
        migrations.AddField(
            model_name='train',
            name='seat_categories',
            field=models.ManyToManyField(related_name='trains_with_category', through='railways.TrainSeatCategory', to='railways.seatcategory'),
        ),
        migrations.CreateModel(
            name='HaltStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_time', models.TimeField()),
                ('departure_time', models.TimeField()),
                ('order', models.IntegerField()),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='halt_station', to='railways.station')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='halt_stations', to='railways.train')),
            ],
            options={
                'unique_together': {('train', 'station', 'order')},
            },
        ),
    ]
