# Generated by Django 5.1.3 on 2024-11-14 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('railways', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='day',
            old_name='day_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='day',
            old_name='day_name',
            new_name='name',
        ),
    ]
