# Generated by Django 5.1.3 on 2024-11-14 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('railways', '0002_rename_day_code_day_code_rename_day_name_day_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='day',
            old_name='code',
            new_name='day_code',
        ),
        migrations.RenameField(
            model_name='day',
            old_name='name',
            new_name='day_name',
        ),
    ]
