# Generated by Django 5.1.3 on 2024-11-14 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railways', '0003_rename_code_day_day_code_rename_name_day_day_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='railways.day'),
        ),
        migrations.AlterField(
            model_name='haltstation',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='halt_station_stops', to='railways.station'),
        ),
    ]
