# Generated by Django 5.1.3 on 2024-11-14 19:06

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railways', '0004_alter_date_day_alter_haltstation_station'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='journey_length',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.CreateModel(
            name='JourneySeatCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_seats', models.IntegerField()),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journey_seat_categories', to='railways.journey')),
                ('seat_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journey_seat_categories', to='railways.seatcategory')),
            ],
        ),
    ]
